/**
 * 389. Find the Difference
 *
 * Given two strings s and t which consist of only lowercase letters.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Find the letter that was added in t.
 *
 * Example:
 *
 * Input:
 * s = "abcd"
 * t = "abcde"
 *
 * Output:
 * e
 *
 * Explanation:
 * 'e' is the letter that was added.
 */
public class FindTheDifference {

    public char findTheDifference(String s, String t) {

        int[] temp = new int[26];
        for (char c : s.toCharArray()) {
            temp[c-'a']++;
        }
        for (char c : t.toCharArray()) {
            temp[c-'a']--;
        }
        for (int i = 0; i < temp.length; i++) {
            if (temp[i] != 0) {
                return (char) (i + 97);
            }
        }
        return 0;
    }

    /**
     * 求字符数组的int和 作差 再转回char
     */
    public char findTheDifference2(String s, String t) {

        char[] sArr = s.toCharArray();
        char[] tArr = t.toCharArray();
        int diff = tArr[sArr.length];
        for (int i = 0; i < sArr.length; i++) {
            diff -= sArr[i];
            diff += tArr[i];
        }
        return (char) diff;
    }

}
